server:
  port: 4004 # Gateway listens on port 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "http://localhost:*"
            allowedMethods: "*"
            allowedHeaders: "*"
            maxAge: 3600
      routes:
        - id: auth-service-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # Route for /api/patients/** to patient-service
        - id: patient-service-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation

        # Route for /api/docs/patients to patient-service /v3/api-docs
        - id: api-docs-patient-route
          uri: http://host.docker.internal:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://host.docker.internal:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://auth-service:4005}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"
